open-feature/python-sdk

open_feature/open_feature_client.py
open_feature/provider/no_op_provider.py
open_feature/provider/provider.py

This PR removes `EvaluationOptions` from all method signatures in the provider's interface as per the breaking changes of v0.4.0 of the OpenFeature spec.
This fixes #10! 
Signed-off-by: Manuel Schönlaub <manuel.schoenlaub@gmail.com>

Remove EvaluationOptions from  method signatures

---

open_feature/provider/metadata.py
open_feature/provider/no_op_metadata.py
open_feature/provider/no_op_provider.py
open_feature/provider/provider.py
tests/provider/test_no_op_provider.py

This PR adds a metadata dataclass to the providers
- New Metadata dataclass that can be extended by the providers

feat: Add metadata to providers

---

open_feature/evaluation_context/evaluation_context.py
open_feature/exception/exceptions.py
open_feature/flag_evaluation/flag_evaluation_details.py
open_feature/hooks/hook_context.py
open_feature/hooks/hook_support.py
open_feature/open_feature_api.py
open_feature/open_feature_client.py
open_feature/provider/no_op_provider.py
open_feature/provider/provider.py
tests/test_open_feature_client.py

Signed-off-by: Manuel Schönlaub <manuel.schoenlaub@gmail.com>
This PR fixes typing errors in the client code:
1. The Liskov Substitution Principle should also apply to providers. This relates to the signature of the methods to retrieve flags.
2. Incorrect usage of `type` instead of `flagType`. Most probably a typo.
3. Ensure that the callables in `create_provider_evaluation` are annotated in a `mypy`-friendly way.
4. Fix type annotations for `FlagEvaluationDetails`
5. Fix type annotations around optional parameters all over the place
Fixes #17

fix: Fix type checking

---

open_feature/flag_evaluation/flag_type.py
open_feature/open_feature_client.py
open_feature/provider/no_op_provider.py
open_feature/provider/provider.py
tests/provider/test_no_op_provider.py
tests/test_open_feature_client.py

- add the possibility for providers to return both `dict` and `list` while calling `get_object_*` functions.
Fixes #63

fix: Get Object should return both list and dict

---

open_feature/open_feature_api.py
tests/test_open_feature_api.py

- initial provider set to a NoOpProvider
- ensures a client will always be returned even if a provider has not been explicitly set
Fixes #1234523
This fixes an issue with spec compliance
~~- Tests~~
Given you have not set a provider
When you retrieve an OpenFeature client
Then an error will not be raised

feat: defaults to NoOpProvider

---

open_feature/open_feature_client.py

- the copied `before` hooks array is not reversed
Tests

fix: reverse the merged before hooks

---

renovate.json

- Explicitly add `requirements-dev.txt` to Renovate config
Renovate isn't detecting the dev dependences because it only looks at `requirements.txt` by default. This can be addressed by added `pip_requirements` as described [here](https://docs.renovatebot.com/python/#alternative-file-names). The currently detected dependencies can be seen [in this issue](https://github.com/open-feature/python-sdk/issues/36).
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>

chore: Add alternative pip file names to renovate config

---

open_feature/flag_evaluation/resolution_details.py
open_feature/provider/no_op_provider.py
open_feature/provider/provider.py

- adds a new `FlagResolutionDetails` class according to the spec
- makes use of the new class in the abstract provider and the no_op provider instead of using `EvaluationDetails`
Fixes #97

chore: split eval and resolution details objects, adjust providers accordingly

---

Makefile
open_feature/flag_evaluation/flag_evaluation_details.py
open_feature/flag_evaluation/reason.py
tests/test_open_feature_client.py
tests/test_open_feature_flag_evaluation.py

- bring FlagEvaluationDetails in-line with the spec
Fixes #98 
make test TEST=tests/test_open_feature_flag_evaluation.py

feat!: EvaluationDetails.reason should be a string, Reason enum should export default reasons per spec

---

open_feature/open_feature_client.py
tests/test_open_feature_client.py

Updates client object methods to accept dict or list as default value.

fix: object client methods can receive dict or list as default_value

---

open_feature/open_feature_client.py

The `_create_provider_evaluation` method is declared as returning a `FlagEvaluationDetails` but actually returned the `FlagResolutionDetails` directly from the provider.
With this change, a `FlagEvaluationDetails` object is created from the resolution details aligning the implementation with the spec and the declared types.
Similar code can found in the Java SDK:
https://github.com/open-feature/java-sdk/blob/9ddc9f1cb2c85c2d096a493342e429120ff36e92/src/main/java/dev/openfeature/sdk/OpenFeatureClient.java#L134

fix: return correct type object in OpenFeatureClient._create_provider_evaluation

---

open_feature/flag_evaluation/flag_type.py
open_feature/open_feature_client.py

Replaces FlagType enum values with standard str objects. Fixes mypy getting tripped up by the definition of FlagType.OBJECT.
Addresses #135

fix: use str values in FlagType enum for easier typing

---

open_feature/open_feature_client.py
tests/test_open_feature_client.py

Implements requirement [1.2.2](https://github.com/open-feature/spec/blob/main/specification/sections/01-flag-evaluation.md#requirement-122):
> The client interface MUST define a metadata member or accessor, containing an immutable name field or accessor of type string, which corresponds to the name value supplied during client creation.

feat: implement client get_metadata for requirement 1.2.2

---

open_feature/hooks/__init__.py
open_feature/open_feature_client.py
readme.md
tests/hooks/test_init.py
tests/test_open_feature_client.py

Implements API-level hooks as defined in the [spec](https://openfeature.dev/specification/sections/hooks/#44-hook-registration--ordering).
Resolves #72
Additional testing around hook evaluation for the OpenFeatureClient is necessary but I wanted to avoid scope creep for this pull request.

feat: implement api-level hooks

---

open_feature/open_feature_api.py
tests/test_open_feature_api.py

Implements requirement [1.1.5](https://github.com/open-feature/spec/blob/main/specification/sections/01-flag-evaluation.md#requirement-115):
> The API MUST provide a function for retrieving the metadata field of the configured provider.

feat: implement get_provider_metadata for requirement 1.1.5

---

open_feature/_backports/strenum.py
open_feature/flag_evaluation/flag_evaluation_details.py
open_feature/flag_evaluation/reason.py
tests/test_open_feature_client.py
tests/test_open_feature_flag_evaluation.py

Is a refinement on #126. In particular, it makes Reason values also instances of str, and thus directly comparable without having to access the `.value` property, and without having to define custom getters and setters in dataclasses.
The motivation for this was to fix a `no-redef` issue reported by mypy in the FlagEvaluationDetails definition:
```
open_feature/flag_evaluation/flag_evaluation_details.py:19: error: Name "reason" already defined on line 15  [no-redef]
```
`StrEnum` is available since Python 3.11 so it requires a minimal backport for earlier Python versions.

refactor: make Reason enum values instances of str

---

open_feature/open_feature_client.py

Makes sure that each `get_<type>_value` method in OpenFeatureClient delegates to the corresponding `get_<type>_details` method. Some of these methods already did so but others called `evaluate_flag_details` directly.
To adhere to a principle of least surprise, remaining methods were adapted to follow a common calling convention.

refactor: make every get_<type>_value function delegate to get_<type>_details

---

open_feature/provider/in_memory_provider.py
tests/provider/test_in_memory_provider.py

Implements an in-memory provider that roughly follows @Kavindu-Dodan proposal in https://github.com/open-feature/ofep/pull/71
A slightly different set of tradeoffs were made regarding the design of the InMemoryFlag object, which should be reviewed carefully. In particular, the State field in the Go implementation was replaced by an explicit Reason which seemed more ergonomic.

feat: implement InMemoryProvider

---

openfeature/client.py
openfeature/flag_evaluation.py
openfeature/provider/in_memory_provider.py
tests/test_client.py
tests/test_flag_evaluation.py

Implements [Requirement 1.4.14](https://openfeature.dev/specification/sections/flag-evaluation#requirement-1414)
> If the flag metadata field in the flag resolution structure returned by the configured provider is set, the evaluation details structure's flag metadata field MUST contain that value. Otherwise, it MUST contain an empty record.

feat: pass flag_metadata from resolution to evaluation details

---

openfeature/hook/hook_support.py

Rewrites the _execute_hooks* functions to be more pythonic. This improves readability and makes the code faster since it avoids the creation of intermediate structures.
I also removed the null guards since the functions are typed as receiving lists always.

refactor: use if clauses in list comprehensions to make code more pythonic

---

openfeature/provider/in_memory_provider.py
tests/features/data.py
tests/provider/test_in_memory_provider.py
tests/test_client.py

- Updated the in-memory provider to throw if the flag isn't found
- Removed duplicate flag keys from the in-memory provider flag config
I marked this as a breaking fix because it changes the method signature of the in-memory provider. Since we're sub-1.0, this will be treated as a minor version change, but highlight the change more predominately in the change log.
I originally intended to only remove the duplicate keys in this PR. If you would prefer that I split these into two separate PRs, please let me know.

fix!: raise error if the flag wasn't found using the in-memory provider

---

pyproject.toml

Adds a py.typed marker file to the `openfeature` package to indicate that the package supports typing, following [PEP 561](https://peps.python.org/pep-0561/#packaging-type-information).

fix: add PEP 561 py.typed marker file

---

openfeature/hook/__init__.py

Corrects type information for some HookContext fields. Yup, it's ugly to prevent a circular import problem, there might be a better way to do it but I haven't found it.

fix: fix types for HookContext.{client,provider}_metadata

---

.flake8
.github/workflows/build.yml
.pre-commit-config.yaml
CONTRIBUTING.md
Makefile
pyproject.toml
requirements.txt

- replace `black`, `flake8` and `isort` with `ruff` and `ruff-format`
- enabled the rules, which replace `flake8` and the plugins you mentioned in the `pre-commit` config
- additionally enabled some more, which I used in an other project, but feel free to enable more, if something peaks your interest 🙂 
- adjusted GHA to use the `pre-commit` action instead
Fixes #219

chore: replace black, fake8 and isort with ruff and ruff-format

---

.github/codeql-config.yml
.github/workflows/build.yml
.github/workflows/lint-pr.yml

- excludes the `tests` from being scanned by CodeQL, which is not needed and improves scanning time
- from ~1:35 to now ~1:18 a small improvement, which will pay off over time with more tests added 🙂 
- added missing permissions restrictions for the GHA workflow files

ci: ignore tests in CodeQL scan and add missing permission restrictions

---

.pre-commit-config.yaml
openfeature/_backports/strenum.py
openfeature/immutable_dict/mapping_proxy_type.py
pyproject.toml

- most of the code has type annotation, so this adds a type checking task inside `pre-commit`, which will be triggered during CI
- had to adjust the `StrEnum` import to use the Python system info, so the type checker can properly handle it
- the ignores in `MappingProxyType` are needed, because the original type hints are different
- plan is to enable more and more `mypy` checks with follow-up PRs till `strict` mode can be enabled

ci: add mypy type checking and fix/exclude minor issues

---

.github/workflows/build.yml

- typically CodeQL scanning takes longer than other steps, therefore it is better to have a dedicated job for it
- also removed the `Install dependencies` step, because there are no dependencies needed for scanning the project (this could change in the future and then it would make sense to split into 2 different `requirements.txt` files or use something like `poetry` to handle dev and runtime dependencies)

ci: split lint job into lint and sast

---

openfeature/_backports/strenum.py
openfeature/api.py
openfeature/client.py
openfeature/hook/__init__.py
openfeature/hook/hook_support.py
openfeature/provider/in_memory_provider.py
openfeature/provider/provider.py
pyproject.toml

- most of the type hint changes are pretty straight forward
- one check of the `strict` checks is disabled to keep this PR rather small
- changed a list-filter-lambda combo to a list comprehension, because `mypy` tripped on it and in general list comprehension are more performant compared to such a combo
- also enabled `mypy` pretty mode, which gives quite nice error outputs
ex. 
```python
openfeature/hook/hook_support.py:52: error: Missing type parameters for generic
type "Mapping"  [type-arg]
hints: typing.Optional[typing.Mapping] = None,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

chore: enable mypy strict mode

---

README.md
openfeature/client.py
openfeature/hook/hook_support.py

Replaces the root logger with a custom logger for all logs emitted by the package. 
I believe this should cover the logging requirements for the SDK, since logs can be manipulated later via handlers and formatters using the standard library `logging` package interface.

feat: improve logging setup

---

openfeature/flag_evaluation.py
tests/test_flag_evaluation.py

Expands the types allowed for `reason` on `FlagEvaluationDetails` and `FlagResolutionDetails` to include both `Reason` and `str` types.
Fixes #262
Related to spec issue: https://github.com/open-feature/spec/issues/236

fix: Allow string values for `FlagEvaluationDetails.reason` and  `FlagResolutionDetails.reason`

---

openfeature/hook/__init__.py
tests/hook/test_hook_support.py

- also added tests to cover section 4.1
Relates #2

feat: make specific fields in HookContext immutable

---

openfeature/api.py
openfeature/client.py
openfeature/provider/__init__.py
openfeature/provider/provider.py
tests/test_api.py

This PR introduces a new FeatureProvider protocol. Public API methods can use it as an argument type when they want to denote any provider, instead of AbstractProvider which is a bit clunky.
AbstractProvider remains as a provider base class for backward compatibility but it's import path at `openfeature.provider.provider` does not have the best ergonomics and we should begin working on a migration path before 1.0 is released.

feat: add FeatureProvider protocol

---

openfeature/api.py
openfeature/client.py

Modifies the `get_provider` and `get_provider_metadata` return types to guarantee that they don't return a `None` value. 
The default provider is initialized as a NoOpProvider at module loading time, so this simplifies the usage of the provider functions for clients.

feat: make return value not optional in provider API functions

---

.pre-commit-config.yaml
pyproject.toml

- Updates ruff version to 0.2.1 and removes deprecated preview flag. Also adds the --fix option to pre-commit hook

chore: update ruff version to 0.2.1 and remove preview flag

---

openfeature/provider/provider.py

Remove `@abstractmethod` decorator which is causing build failures in https://github.com/open-feature/python-sdk-contrib/pull/37#issuecomment-1936528976
The method already provides a default implementation.

refactor: remove abstractmethod decorator from get_provider_hooks

---

README.md
openfeature/api.py
openfeature/client.py
openfeature/provider/registry.py
tests/features/steps/steps.py
tests/test_api.py
tests/test_client.py

Adds support for domains with a minimalist implementation. Feedback is especially welcome around public APIs and backward compatibility issues.
Builds on top of https://github.com/open-feature/python-sdk/pull/270
Refs https://github.com/open-feature/python-sdk/issues/125

feat!: add support for domains

---

openfeature/flag_evaluation.py
openfeature/hook/__init__.py
openfeature/hook/hook_support.py
tests/hook/test_hook_support.py

- it doesn't really enforce `4.2.2.1`, but a type checker will complain, if you try to change a value in the hook hints
- had to switch from `dataclass` to a normal class `HookContext` to make the metadata fields immutable

refactor: improve Hook Hints typing

---

README.md

Just a simple doc update to add missing imports to the sample code.

docs: Add Missing Imports in Provider Dev Example in README

---

README.md

Release-As: 0.6.0
Update spec badge to `0.8.0` as I believe this better represents the current SDK version.
We should still double-check that we aren't missing anything important but most of the 0.8.0 stuff is implemented as of today.

docs: update spec version to 0.8.0

---

openfeature/event.py

`PROVIDER_FATAL` event does not exist. The FATAL status is reported through a PROVIDER_ERROR event.
See https://openfeature.dev/specification/types#provider-events

fix: remove ProviderEvent.PROVIDER_FATAL

---

.github/workflows/build.yml
openfeature/api.py
openfeature/client.py
openfeature/evaluation_context.py
openfeature/event.py
openfeature/exception.py
openfeature/flag_evaluation.py
openfeature/hook/__init__.py
openfeature/provider/__init__.py
openfeature/provider/provider.py

Refs https://github.com/open-feature/python-sdk/issues/214
Note: this is a breaking change. We should do an ecosystem check to make sure most packages are using the correct imports.

fix!: restrict exported names with __all__

---

README.md
openfeature/_event_support.py
openfeature/event.py
openfeature/provider/__init__.py
openfeature/provider/in_memory_provider.py
openfeature/provider/no_op_provider.py
openfeature/provider/provider.py

Moves `AbstractProvider` to `openfeature.provider` module.
Had to reverse the dependency direction between ProviderStatus and ProviderEvent to avoid a circular dependency.
This release SHOULD allow providers to seamlessly support previous and current versions as long as they update their code before 0.7.0 comes out.

refactor!: move AbstractProvider to openfeature.provider

---

openfeature/provider/__init__.py
openfeature/provider/_registry.py
tests/test_api.py

This opens the door to handling events for child providers inside composite providers.

refactor: bind providers explicitly to a registry with attach/detach

---

openfeature/_event_support.py
tests/test_client.py

The _client_handlers dictionary allowed modifications during iteration without proper concurrency control. I added some reentrant locks to manage concurrent access to the _global_handlers and _client_handlers data structures.
See #326 
Perhaps there is a way to implement some finer-grained concurrency control? The Java SDK uses a ConcurrentHashMap that allows retrieval operations without locking, but I haven't looked into the details.

fix: event handler methods are not thread-safe

---

openfeature/client.py

- remove exception logging during evaluation
https://github.com/open-telemetry/opentelemetry-demo/issues/1628
The OTel demo was seeing overly verbose log messages when they disabled a flag. That's because a `FLAG_NOT_FOUND` error was raised by the provider, and the SDK was logging all exceptions. I've updated the SDK to no longer log OpenFeatureErrors since providers commonly raise these, which can lead to log spam. It's worth noting that this information can still be accessed via a hook or evaluation details.

fix: remove exception logging during evaluation

---

.github/workflows/release.yml
release-please-config.json

- run release please as the OpenFeature bot
This should allow GitHub actions to run when release please opens a release PR.

ci: run release please as OpenFeature bot

---

README.md
openfeature/api.py
openfeature/client.py
openfeature/transaction_context/__init__.py
openfeature/transaction_context/context_var_transaction_context_propagator.py
openfeature/transaction_context/no_op_transaction_context_propagator.py
openfeature/transaction_context/transaction_context_propagator.py
pyproject.toml
tests/test_client.py
tests/test_transaction_context.py

Implements transaction context as described in #292.
This is done the same as in Node, the callback we have for Node is not needed with context vars, like it is in Java.
@federicobond just after I did the changes I saw you PR from May:
Sorry, I could have just continued test on this one. 
We basically did the same but I added some tests also for the context merging.

feat: implement transaction context

---

.gitmodules
tests/features/data.py
tests/features/steps/flag_steps.py
tests/features/steps/metadata_steps.py
tests/features/steps/steps.py

Adds gherkin tests for flag metadata on evaluation.
This PR depends on, and is blocked by, [https://github.com/open-feature/spec/pull/289](https://github.com/open-feature/spec/pull/289)
Fixes #1467 ([https://github.com/open-feature/flagd/issues/1467](https://github.com/open-feature/flagd/issues/1467))

feat: Update test harness (add assertions) #1467

---

.github/workflows/release.yml

- removes the Python container from the GitHub action runner
- adds the Python action
- removes pypi release version restriction
Confirmed to work in the Python contrib repo: https://github.com/open-feature/python-sdk-contrib/pull/159

ci: update release process

---

.gitmodules
pyproject.toml
tests/features/steps/steps.py

Addendum to [https://github.com/open-feature/python-sdk/pull/415](https://github.com/open-feature/python-sdk/pull/415). Removes the `test-harness` submodule and temporarily copies the gherkin test files to the `tests` folder while the tests run.
Fixes #1467 ([https://github.com/open-feature/flagd/issues/1467](https://github.com/open-feature/flagd/issues/1467))

feat: Update test harness (copy test files) #1467

---

openfeature/client.py
tests/test_client.py

Calls the finally hooks after flag evaluation was attempted, even whe nthe provider is not in a ready state.
Fixes #424

fix: Finally hooks do not get called when the provider is not ready #424

---

openfeature/client.py
openfeature/hook/__init__.py
openfeature/hook/_hook_support.py
pyproject.toml
tests/features/steps/hooks_steps.py
tests/features/steps/steps.py
tests/hook/test_hook_support.py

Adds the evaluation details to the finally hook
Fixes #403 
Please make sure the e2e tests work, especially the part with `git submodule add --force https://github.com/open-feature/spec.git spec` in `pyproject.toml`.

feat: Add evaluation details to finally hook stage #403

---

README.md

1) The parameter in the form has changed from `python` to `Python`.
Now the link from readme.md goes to a blank page.
2) I also added end_slash to the link, if the site does it, then why not do it right away.
This is not a problem_PROBLEM, but if it can be fixed, why not fix it.
Chrome incognito mode

docs: fix links to the openfeature ecosystem page

---

.github/workflows/release.yml
renovate.json

Extends the [centralized Renovate config](https://github.com/open-feature/community-tooling/blob/main/renovate.json) and downgrades Release Please to v3.

chore: use centralized renovate config, downgrade release please

---

.github/workflows/build.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
openfeature/_event_support.py
openfeature/api.py
openfeature/client.py
openfeature/event.py
openfeature/flag_evaluation.py
openfeature/hook/__init__.py
openfeature/hook/_hook_support.py
openfeature/provider/__init__.py
openfeature/provider/_registry.py
openfeature/provider/in_memory_provider.py
openfeature/provider/no_op_provider.py
pyproject.toml

- I think it is time to say goodbye to Python 3.8 support, `mypy` dropped 3.8 support in its latest version and the flagd test suite will benefit from it

chore!: drop Python 3.8 support

---

pyproject.toml

- modifies the submodule set in the E2E tests to use the existing `.gitmodule` configuration.
The E2E tests will now use the submodule sha instead of pulling the latest. As a added benefit, Renovate should automagically open PRs when the spec repo is updated.

chore: use existing submodule version for e2e tests

---

openfeature/client.py
tests/test_client.py

Cleaning up some tech debt associated mentioned in this [comment](https://github.com/open-feature/python-sdk/pull/413#discussion_r1940218118)
* Dynamically resolve based on keyword arguments
* I wasn't able to find a configuration that worked on python 3.8/3.9 with mypy. I opted for ignoring the call-arg.
* If we'd prefer not ignore the error and keep positional arguments, feel free to close the PR.
Standard testing (test, e2e, pre-commit)

chore: use keyword arguments, validate test

---

CODEOWNERS

All the other sdks use codeowner files to ensure proper approvals, we should also utilize this within python-sdk

chore: add codeowner file to be consistent with the rest of openfeature

---

openfeature/client.py
openfeature/flag_evaluation.py
openfeature/provider/in_memory_provider.py
tests/provider/test_in_memory_provider.py
tests/test_client.py

- this has actually no consequences for SDK users, because we already properly sending the errors inside the flag evaluation and only internally raised an exception. if someone used the privately marked methods, then it is a breaking change for them, but that's nothing we guarantee stability for.
Fixes #466

refactor: replace exception raising with error flag resolution

---

openfeature/client.py
tests/test_transaction_context_in_hooks.py

Currently during flag evaluation the transaction context is merged into the evaluation context here: https://github.com/open-feature/python-sdk/blob/288bd6bb34f2d5e857ae5b2b17f02f79276049c5/openfeature/client.py#L778
However the `hook_context.evaluation_context` is created before this, so it doesn't contain the attributes or targeting key that exists in the propagated transaction context. This is unexpected. It is also different than what [the JS implementation does.](https://github.com/open-feature/js-sdk/blob/d8bd93b6d5256445d12185d639e1cd91800a8a16/packages/server/src/client/internal/open-feature-client.ts#L277)
In this PR:
1. The transaction context is merged with the evaluation context  in `_establish_hooks_and_provider` before creating the hook context. 
2. The …

fix: merge transaction context into hook context evaluation context (#521)

---

.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
renovate.json
uv.lock

- switched build backend from hatch to uv
- pinned the uv version to 0.8.x to be better control updates
- enabled uv.lock updates via renovate
- some minor cleanup

chore: switch build backend to uv

---

.github/workflows/build.yml
tests/test_client.py

- still a bit time till GA, but the first RC came out

chore: support Python 3.14

---

scripts/scripts.py

- also replaced the `cp` and `rm` commands with proper Python code

chore: remove shell flag usage in project scripts
