open_feature/evaluation_context/evaluation_context.py, open_feature/open_feature_client.py, tests/evaluation_context/test_evaluation_context.py
An initial implementation of the evaluation context spec of Open Feature seen here https://github.com/open-feature/spec/blob/main/specification/evaluation-context.md
=> evaluation-context: Add evaluation context to open feature

open_feature/evaluation_context/evaluation_context.py, open_feature/hooks/hook.py, open_feature/hooks/hook_context.py, open_feature/hooks/hook_support.py, open_feature/hooks/hook_type.py, open_feature/open_feature_api.py, open_feature/open_feature_client.py, open_feature/open_feature_evaluation_context.py, open_feature/provider/no_op_provider.py, open_feature/provider/provider.py, tests/hooks/conftest.py, tests/hooks/test_hook_support.py
Signed-off-by: Andrew Helsby <ajhelsby@hotmail.com>
=> hooks: Implementation of hooks for python OpenFeature

readme.md
- docs update. Adds a Python badge showing the supported versions.
Fixes #1234523
So very inconsequential, but badges are the first place a lot of people look (including me).
Make sure to update the version here too :slightly_smiling_face: 
1. Open the README.md
2. Read badges
3. Confirm it says "Python >=3.8"
=> docs: add badge showing supported Python version range

.github/workflows/release.yml
=> feat: Fix release workflow

.github/workflows/release.yml
Run a single container for sdk release
=> feat: Run a single container for sdk release

.github/workflows/release.yml
The release job requires the result of the release-please job, therefore a needs parameter has been added to the release job.
=> feat: Add needs to release job

readme.md
- Updates the OpenFeature name in the title
- Formats the readme based on prettier defaults
- Bumps the version in the install instructions
- Sets Release Please comments to automatically control the version bump for future releases
The next Release Please PR should automatically bump the version numbers mentioned on the readme.
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: update readme to include latest pip version

readme.md
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
- Updates readme with latest install instructions.
Fixes #56
=> docs: Update pip install instructions

readme.md
- updates docs to include import for `NoOpProvider`
Fixes #61
=> docs: add NoOpProvider import to config sample

renovate.json
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: Configure Renovate auto merge

readme.md
- Uses the standard readme template
- added additional examples for context
Fixes #100
=> chore: Update readme with standard format and examples

openfeature/client.py, openfeature/flag_evaluation.py, openfeature/hook/__init__.py, openfeature/hook/hook_support.py, openfeature/provider/in_memory_provider.py, pyproject.toml, tests/conftest.py, tests/hook/test_hook_support.py, tests/provider/test_in_memory_provider.py, tests/test_flag_evaluation.py
- follow-up to #249 to remove the excluded `ruff` rules
- there are no logic changes, just syntactical
=> chore: remove excluded ruff rules and fix issues

.github/workflows/release.yml
@beeme1mr would be great, if you can add what I wrote in the comment of the linked issue, then this should be good to go 💪 
Relates #231
=> ci: use pypi trusted publishing

README.md
Updates the supported spec version to 0.5.2 in README. Also marks logging feature as supported.
=> docs: update supported spec version

release-please-config.json
Fixes: https://github.com/open-feature/python-sdk/issues/279
This is consistent with other repos.
=> chore: add changelog sections

openfeature/client.py
Also ensures provider consistency during flag evaluation.
Closes #301
=> feat: populate provider and client metadata in HookContext 

.github/workflows/build.yml
See https://cloud-native.slack.com/archives/C0344AANLA1/p1712852328361719
=> chore: update codecov/codecov-action action to v4

.github/workflows/release.yml
=> build: pin pypi release GHA to v1.11

README.md
@beeme1mr You merge https://github.com/open-feature/python-sdk/pull/432 too fast =)
here is 1 more fix docs
=> docs: fix eval context link

openfeature/client.py
=> chore: improve resolve details callable type hints

openfeature/provider/__init__.py
=> fix: add passthrough init to abstract provider
